		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	  <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/knockout/3.1.0/knockout-min.js"></script>
	  <script>window.jQuery || document.write('<script src="js/vendor/knockout-min.js"><\/script>')</script>
	  <!-- TODO: Switch to min for production -->
	  <script src="js/scripts.js"></script>
	</body>
</html>